<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
	<TargetFramework>net472</TargetFramework>
	<LangVersion>latest</LangVersion>
	<Nullable>enable</Nullable>
	<RootNamespace>MPW</RootNamespace>
	<SignAssembly>true</SignAssembly>
	<AssemblyOriginatorKeyFile>MPW.API.snk</AssemblyOriginatorKeyFile>
	<GenerateAssemblyInfo>false</GenerateAssemblyInfo>
	<OutputPath>bin\$(Configuration)\</OutputPath>
	<AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
	<GameDllsDir>..\..\..\People Playground_Data\Managed</GameDllsDir>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
	<DefineConstants>DEBUG;TRACE</DefineConstants>
	<DocumentationFile>bin\Debug\MPW.API.xml</DocumentationFile>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
	<DefineConstants>TRACE</DefineConstants>
  </PropertyGroup>

  <ItemGroup>
	<PackageReference Include="Microsoft.Bcl.HashCode" Version="6.0.0" />
	<PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.0.9" />
	<PackageReference Include="ObservableCollections" Version="3.3.4" />
  </ItemGroup>

  <ItemGroup>
	<Reference Include="Assembly-CSharp">
	  <HintPath>$(GameDllsDir)\Assembly-CSharp.dll</HintPath>
	  <Private>False</Private>
	</Reference>
	<Reference Include="Unity.TextMeshPro">
	  <HintPath>$(GameDllsDir)\Unity.TextMeshPro.dll</HintPath>
	  <Private>False</Private>
	</Reference>
	<Reference Include="UnityEngine">
	  <HintPath>$(GameDllsDir)\UnityEngine.dll</HintPath>
	  <Private>False</Private>
	</Reference>
	<Reference Include="UnityEngine.CoreModule">
	  <HintPath>$(GameDllsDir)\UnityEngine.CoreModule.dll</HintPath>
	  <Private>False</Private>
	</Reference>
	<Reference Include="UnityEngine.TextCoreModule">
	  <HintPath>$(GameDllsDir)\UnityEngine.TextCoreModule.dll</HintPath>
	  <Private>False</Private>
	</Reference>
	<Reference Include="UnityEngine.TextRenderingModule">
	  <HintPath>$(GameDllsDir)\UnityEngine.TextRenderingModule.dll</HintPath>
	  <Private>False</Private>
	</Reference>
	<Reference Include="UnityEngine.UI">
	  <HintPath>$(GameDllsDir)\UnityEngine.UI.dll</HintPath>
	  <Private>False</Private>
	</Reference>
	<Reference Include="System.Data" />
	<Reference Include="Microsoft.CSharp" />
  </ItemGroup>

  <ItemGroup>
	<ProjectReference Include="..\..\..\..\..\..\..\..\..\..\Programming\CSharp\Unity.AdvancedUI\Unity.AdvancedUI.csproj" />
  </ItemGroup>

</Project>